--------------------------------------------------------
--  File created - Wednesday-January-12-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UNIVERSITY
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."UNIVERSITY" 
   (	"UNI_ID" VARCHAR2(4 BYTE), 
	"UNI_NAME" VARCHAR2(60 BYTE), 
	"UNI_IS_PARTNER" VARCHAR2(3 BYTE), 
	"UNI_AGREEMENT" VARCHAR2(3 BYTE), 
	"UNI_COUNTRY" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007088
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."SYS_C007088" ON "STUDENTEXCHANGE"."UNIVERSITY" ("UNI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007089
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."SYS_C007089" ON "STUDENTEXCHANGE"."UNIVERSITY" ("UNI_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table UNIVERSITY
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."UNIVERSITY" MODIFY ("UNI_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."UNIVERSITY" MODIFY ("UNI_NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."UNIVERSITY" MODIFY ("UNI_IS_PARTNER" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."UNIVERSITY" MODIFY ("UNI_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."UNIVERSITY" ADD PRIMARY KEY ("UNI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."UNIVERSITY" ADD UNIQUE ("UNI_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;


--------------------------------------------------------
--  File created - Wednesday-January-12-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."STAFF" 
   (	"STAFF_ID" VARCHAR2(4 BYTE), 
	"STAFF_NAME" VARCHAR2(30 BYTE), 
	"STAFF_EMAIL" VARCHAR2(30 BYTE), 
	"STAFF_CONTACT_NUMBER" VARCHAR2(20 BYTE), 
	"STAFF_JOB" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."STAFF_PK" ON "STUDENTEXCHANGE"."STAFF" ("STAFF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STAFF_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."STAFF_UK1" ON "STUDENTEXCHANGE"."STAFF" ("STAFF_ID", "STAFF_EMAIL", "STAFF_CONTACT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."STAFF" ADD CONSTRAINT "STAFF_UK1" UNIQUE ("STAFF_ID", "STAFF_EMAIL", "STAFF_CONTACT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("STAFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."STAFF" MODIFY ("STAFF_JOB" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."STAFF" MODIFY ("STAFF_CONTACT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."STAFF" MODIFY ("STAFF_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."STAFF" MODIFY ("STAFF_NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."STAFF" MODIFY ("STAFF_ID" NOT NULL ENABLE);


--------------------------------------------------------
--  File created - Wednesday-January-12-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UNI_COORD
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."UNI_COORD" 
   (	"COORD_ID" VARCHAR2(4 BYTE), 
	"UNI_ID" VARCHAR2(4 BYTE), 
	"COORD_NAME" VARCHAR2(30 BYTE), 
	"COORD_EMAIL" VARCHAR2(30 BYTE), 
	"COORD_CONTACT_NUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COORDINATOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."COORDINATOR_PK" ON "STUDENTEXCHANGE"."UNI_COORD" ("COORD_ID", "UNI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COORDINATOR_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."COORDINATOR_UK1" ON "STUDENTEXCHANGE"."UNI_COORD" ("UNI_ID", "COORD_EMAIL", "COORD_CONTACT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table UNI_COORD
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."UNI_COORD" ADD CONSTRAINT "COORDINATOR_UK1" UNIQUE ("UNI_ID", "COORD_EMAIL", "COORD_CONTACT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."UNI_COORD" ADD CONSTRAINT "COORDINATOR_PK" PRIMARY KEY ("COORD_ID", "UNI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."UNI_COORD" MODIFY ("COORD_CONTACT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."UNI_COORD" MODIFY ("COORD_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."UNI_COORD" MODIFY ("COORD_NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."UNI_COORD" MODIFY ("UNI_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."UNI_COORD" MODIFY ("COORD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table UNI_COORD
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."UNI_COORD" ADD CONSTRAINT "UNI_COORD_FK1" FOREIGN KEY ("UNI_ID")
	  REFERENCES "STUDENTEXCHANGE"."UNIVERSITY" ("UNI_ID") ENABLE;



--------------------------------------------------------
--  DDL for Table FEE
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."FEE" 
   (	"FEE_CODE" VARCHAR2(4 BYTE), 
	"ADMIN_FEE" NUMBER, 
	"TUITION_FEE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."FEE_PK" ON "STUDENTEXCHANGE"."FEE" ("FEE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FEE
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."FEE" ADD CONSTRAINT "FEE_PK" PRIMARY KEY ("FEE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."FEE" MODIFY ("TUITION_FEE" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."FEE" MODIFY ("ADMIN_FEE" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."FEE" MODIFY ("FEE_CODE" NOT NULL ENABLE);



--------------------------------------------------------
--  DDL for Table INBOUND_PROGRAM
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."INBOUND_PROGRAM" 
   (	"INPROG_ID" VARCHAR2(5 BYTE), 
	"INPROG_TYPE" VARCHAR2(10 BYTE), 
	"INPROG_DURATION" NUMBER, 
	"INPROG_STARTDATE" DATE, 
	"FEE_CODE" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INBOUND_PROGRAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."INBOUND_PROGRAM_PK" ON "STUDENTEXCHANGE"."INBOUND_PROGRAM" ("INPROG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INBOUND_PROGRAM_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."INBOUND_PROGRAM_UK1" ON "STUDENTEXCHANGE"."INBOUND_PROGRAM" ("FEE_CODE", "INPROG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INBOUND_PROGRAM
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_PROGRAM" ADD CONSTRAINT "INBOUND_PROGRAM_UK1" UNIQUE ("FEE_CODE", "INPROG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_PROGRAM" ADD CONSTRAINT "INBOUND_PROGRAM_PK" PRIMARY KEY ("INPROG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_PROGRAM" MODIFY ("FEE_CODE" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_PROGRAM" MODIFY ("INPROG_STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_PROGRAM" MODIFY ("INPROG_DURATION" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_PROGRAM" MODIFY ("INPROG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_PROGRAM" MODIFY ("INPROG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table INBOUND_PROGRAM
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_PROGRAM" ADD CONSTRAINT "INBOUND_PROGRAM_FK1" FOREIGN KEY ("FEE_CODE")
	  REFERENCES "STUDENTEXCHANGE"."FEE" ("FEE_CODE") ENABLE;



--------------------------------------------------------
--  DDL for Table FINANCIAL_AID
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."FINANCIAL_AID" 
   (	"FIN_ORG" VARCHAR2(30 BYTE), 
	"FIN_AID_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FINANCIAL_AID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."FINANCIAL_AID_PK" ON "STUDENTEXCHANGE"."FINANCIAL_AID" ("FIN_ORG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FINANCIAL_AID
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."FINANCIAL_AID" ADD CONSTRAINT "FINANCIAL_AID_PK" PRIMARY KEY ("FIN_ORG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."FINANCIAL_AID" MODIFY ("FIN_AID_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."FINANCIAL_AID" MODIFY ("FIN_ORG" NOT NULL ENABLE);



--------------------------------------------------------
--  DDL for Table FACULTY
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."FACULTY" 
   (	"FAC_CODE" VARCHAR2(2 BYTE), 
	"FAC_NAME" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FACULTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."FACULTY_PK" ON "STUDENTEXCHANGE"."FACULTY" ("FAC_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FACULTY
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."FACULTY" ADD CONSTRAINT "FACULTY_PK" PRIMARY KEY ("FAC_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."FACULTY" MODIFY ("FAC_NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."FACULTY" MODIFY ("FAC_CODE" NOT NULL ENABLE);



--------------------------------------------------------
--  DDL for Table MODULE
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."MODULE" 
   (	"MODULE_CODE" VARCHAR2(5 BYTE), 
	"MODULE_NAME" VARCHAR2(30 BYTE), 
	"CREDIT_HOUR" NUMBER, 
	"FAC_CODE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MODULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."MODULE_PK" ON "STUDENTEXCHANGE"."MODULE" ("MODULE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MODULE
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."MODULE" ADD CONSTRAINT "MODULE_PK" PRIMARY KEY ("MODULE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."MODULE" MODIFY ("FAC_CODE" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."MODULE" MODIFY ("CREDIT_HOUR" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."MODULE" MODIFY ("MODULE_NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."MODULE" MODIFY ("MODULE_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MODULE
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."MODULE" ADD CONSTRAINT "MODULE_FK1" FOREIGN KEY ("FAC_CODE")
	  REFERENCES "STUDENTEXCHANGE"."FACULTY" ("FAC_CODE") ENABLE;



--------------------------------------------------------
--  DDL for Table OUTBOUND_PROGRAM
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."OUTBOUND_PROGRAM" 
   (	"OUTPROG_ID" VARCHAR2(5 BYTE), 
	"OUTPROG_TYPE" VARCHAR2(10 BYTE), 
	"OUTPROG_DURATION" NUMBER, 
	"OUTPROG_STARTDATE" DATE, 
	"UNI_ID" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OUTBOUND_PROGRAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."OUTBOUND_PROGRAM_PK" ON "STUDENTEXCHANGE"."OUTBOUND_PROGRAM" ("OUTPROG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table OUTBOUND_PROGRAM
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_PROGRAM" ADD CONSTRAINT "OUTBOUND_PROGRAM_PK" PRIMARY KEY ("OUTPROG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_PROGRAM" MODIFY ("UNI_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_PROGRAM" MODIFY ("OUTPROG_STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_PROGRAM" MODIFY ("OUTPROG_DURATION" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_PROGRAM" MODIFY ("OUTPROG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_PROGRAM" MODIFY ("OUTPROG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OUTBOUND_PROGRAM
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_PROGRAM" ADD CONSTRAINT "OUTBOUND_PROGRAM_FK1" FOREIGN KEY ("UNI_ID")
	  REFERENCES "STUDENTEXCHANGE"."UNIVERSITY" ("UNI_ID") ENABLE;



--------------------------------------------------------
--  DDL for Table OUTBOUND_STUDENT
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" 
   (	"OUTSTU_ID" VARCHAR2(5 BYTE), 
	"OUTSTU_NAME" VARCHAR2(30 BYTE), 
	"OUTSTU_GENDER" VARCHAR2(6 BYTE), 
	"OUTSTU_LEVEL_OF_STUDY" NUMBER, 
	"OUTSTU_EMAIL" VARCHAR2(30 BYTE), 
	"OUTPROG_ID" VARCHAR2(5 BYTE), 
	"STAFF_ID" VARCHAR2(4 BYTE), 
	"FIN_ORG" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OUTBOUND_STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."OUTBOUND_STUDENT_PK" ON "STUDENTEXCHANGE"."OUTBOUND_STUDENT" ("OUTSTU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OUTBOUND_STUDENT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."OUTBOUND_STUDENT_UK1" ON "STUDENTEXCHANGE"."OUTBOUND_STUDENT" ("OUTSTU_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table OUTBOUND_STUDENT
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" ADD CONSTRAINT "OUTBOUND_STUDENT_UK1" UNIQUE ("OUTSTU_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" ADD CONSTRAINT "OUTBOUND_STUDENT_PK" PRIMARY KEY ("OUTSTU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" MODIFY ("STAFF_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" MODIFY ("OUTPROG_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" MODIFY ("OUTSTU_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" MODIFY ("OUTSTU_LEVEL_OF_STUDY" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" MODIFY ("OUTSTU_GENDER" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" MODIFY ("OUTSTU_NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" MODIFY ("OUTSTU_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OUTBOUND_STUDENT
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" ADD CONSTRAINT "OUTBOUND_STUDENT_FK1" FOREIGN KEY ("OUTPROG_ID")
	  REFERENCES "STUDENTEXCHANGE"."OUTBOUND_PROGRAM" ("OUTPROG_ID") ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" ADD CONSTRAINT "OUTBOUND_STUDENT_FK2" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "STUDENTEXCHANGE"."STAFF" ("STAFF_ID") ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."OUTBOUND_STUDENT" ADD CONSTRAINT "OUTBOUND_STUDENT_FK3" FOREIGN KEY ("FIN_ORG")
	  REFERENCES "STUDENTEXCHANGE"."FINANCIAL_AID" ("FIN_ORG") ENABLE;



--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."PAYMENT" 
   (	"PAYMENT_ID" VARCHAR2(4 BYTE), 
	"PAYEMNT_METHOD" VARCHAR2(30 BYTE), 
	"FEE_CODE" VARCHAR2(4 BYTE), 
	"FIN_ORG" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."PAYMENT_PK" ON "STUDENTEXCHANGE"."PAYMENT" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."PAYMENT" ADD CONSTRAINT "PAYMENT_PK" PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."PAYMENT" MODIFY ("FEE_CODE" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."PAYMENT" MODIFY ("PAYEMNT_METHOD" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."PAYMENT" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."PAYMENT" ADD CONSTRAINT "PAYMENT_FK1" FOREIGN KEY ("FEE_CODE")
	  REFERENCES "STUDENTEXCHANGE"."FEE" ("FEE_CODE") ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."PAYMENT" ADD CONSTRAINT "PAYMENT_FK2" FOREIGN KEY ("FIN_ORG")
	  REFERENCES "STUDENTEXCHANGE"."FINANCIAL_AID" ("FIN_ORG") ENABLE;



--------------------------------------------------------
--  DDL for Table INBOUND_STUDENT
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" 
   (	"INSTU_ID" VARCHAR2(5 BYTE), 
	"INSTU_NAME" VARCHAR2(30 BYTE), 
	"INSTU_GENDER" VARCHAR2(6 BYTE), 
	"INSTU_LEVEL_OF_STUDY" NUMBER, 
	"INSTU_NATIONALITY" VARCHAR2(60 BYTE), 
	"INSTU_EMAIL" VARCHAR2(30 BYTE), 
	"INPROG_ID" VARCHAR2(5 BYTE), 
	"UNI_ID" VARCHAR2(4 BYTE), 
	"COORD_ID" VARCHAR2(4 BYTE), 
	"PAYMENT_ID" VARCHAR2(4 BYTE), 
	"FIN_ORG" VARCHAR2(30 BYTE), 
	"STAFF_ID" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INBOUND_STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."INBOUND_STUDENT_PK" ON "STUDENTEXCHANGE"."INBOUND_STUDENT" ("INSTU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INBOUND_STUDENT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."INBOUND_STUDENT_UK1" ON "STUDENTEXCHANGE"."INBOUND_STUDENT" ("INSTU_ID", "INSTU_EMAIL", "PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INBOUND_STUDENT
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" ADD CONSTRAINT "INBOUND_STUDENT_UK1" UNIQUE ("INSTU_ID", "INSTU_EMAIL", "PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" ADD CONSTRAINT "INBOUND_STUDENT_PK" PRIMARY KEY ("INSTU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("STAFF_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("COORD_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("UNI_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("INPROG_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("INSTU_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("INSTU_NATIONALITY" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("INSTU_LEVEL_OF_STUDY" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("INSTU_GENDER" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("INSTU_NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" MODIFY ("INSTU_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table INBOUND_STUDENT
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" ADD CONSTRAINT "INBOUND_STUDENT_FK1" FOREIGN KEY ("INPROG_ID")
	  REFERENCES "STUDENTEXCHANGE"."INBOUND_PROGRAM" ("INPROG_ID") ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" ADD CONSTRAINT "INBOUND_STUDENT_FK2" FOREIGN KEY ("COORD_ID", "UNI_ID")
	  REFERENCES "STUDENTEXCHANGE"."UNI_COORD" ("COORD_ID", "UNI_ID") ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" ADD CONSTRAINT "INBOUND_STUDENT_FK3" FOREIGN KEY ("FIN_ORG")
	  REFERENCES "STUDENTEXCHANGE"."FINANCIAL_AID" ("FIN_ORG") ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" ADD CONSTRAINT "INBOUND_STUDENT_FK4" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "STUDENTEXCHANGE"."STAFF" ("STAFF_ID") ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."INBOUND_STUDENT" ADD CONSTRAINT "INBOUND_STUDENT_FK5" FOREIGN KEY ("PAYMENT_ID")
	  REFERENCES "STUDENTEXCHANGE"."PAYMENT" ("PAYMENT_ID") ENABLE;



--------------------------------------------------------
--  DDL for Table ENROLL
--------------------------------------------------------

  CREATE TABLE "STUDENTEXCHANGE"."ENROLL" 
   (	"MODULE_CODE" VARCHAR2(5 BYTE), 
	"INSTU_ID" VARCHAR2(5 BYTE), 
	"ENROLL_DATE" DATE, 
	"ENROLL_GRADE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENROLL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENTEXCHANGE"."ENROLL_PK" ON "STUDENTEXCHANGE"."ENROLL" ("MODULE_CODE", "INSTU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ENROLL
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."ENROLL" ADD CONSTRAINT "ENROLL_PK" PRIMARY KEY ("MODULE_CODE", "INSTU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."ENROLL" MODIFY ("ENROLL_DATE" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."ENROLL" MODIFY ("INSTU_ID" NOT NULL ENABLE);
  ALTER TABLE "STUDENTEXCHANGE"."ENROLL" MODIFY ("MODULE_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ENROLL
--------------------------------------------------------

  ALTER TABLE "STUDENTEXCHANGE"."ENROLL" ADD CONSTRAINT "ENROLL_FK1" FOREIGN KEY ("MODULE_CODE")
	  REFERENCES "STUDENTEXCHANGE"."MODULE" ("MODULE_CODE") ENABLE;
  ALTER TABLE "STUDENTEXCHANGE"."ENROLL" ADD CONSTRAINT "ENROLL_FK2" FOREIGN KEY ("INSTU_ID")
	  REFERENCES "STUDENTEXCHANGE"."INBOUND_STUDENT" ("INSTU_ID") ENABLE;



