SELECT COORD_ID, COORD_NAME, OUTSTU_ID, OUTSTU_NAME, OUTSTU_GENDER, OUTPROG_TYPE, OUTPROG_DURATION
FROM UNI_COORD
INNER JOIN OUTBOUND_PROGRAM
ON UNI_COORD.UNI_ID = OUTBOUND_PROGRAM.UNI_ID
INNER JOIN OUTBOUND_STUDENT
ON OUTBOUND_PROGRAM.OUTPROG_ID = OUTBOUND_STUDENT.OUTPROG_ID
WHERE COORD_NAME = 'Allen' AND OUTPROG_TYPE = 'short_term'
ORDER BY COORD_NAME;